name: RPG
version: '1.0-SNAPSHOT'
main: my.rpg.rPG.RPG
api-version: '1.21'
description: quick test to know how it works

commands:
  squidGame:
    description: Test command
    usage: /squidGame
  light:
    description: make light
    usage: /light