name: RPG
version: '1.0-SNAPSHOT'
main: my.hns.Main
api-version: '1.21'
description: quick test to know how it works

commands:
  squidGame:
    description: Test command
    usage: /squidGame
  StartGame:
    description: StartTheGame
    usage: /StartGame
  join:
    description: Join the game
    usage: /join <hider | seeker>
  team:
    description: team list
    usage: /team